### MARK: Rule Definitions

# Default rule identifiers turned on automatically that need to be disabled
disabled_rules:
  - inclusive_language

# Opt-in rule identifiers turned off automatically that need to be enabled
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - file_types_order
  - final_test_case
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
# Note: Enable before releasing v1.0.0
#  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_empty_block
  - no_grouping_extension
  - no_magic_numbers
  - non_overridable_class_declaration
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_subject
  - private_swiftui_state
  - prohibited_interface_builder
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - superfluous_else
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Analyzer rule identifiers turned off automatically that need to be enabled
# Note: The rules are ran using `swiftlint analyze`
analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

### MARK: Rule Configurations

##### Configuration examples:
#
### Binary rules
#
# Implicitly:
#   force_cast: warning
# Explicitly:
#   force_try:
#     severity: warning
#
### Warning & Error Level Rules
#
# Note: Can set just the warning level
# Implicitly:
#   line_length: 120 # warning
#   type_body_length:
#       - 300 # warning
#       - 400 # error
# Explicitly:
#   file_length:
#       warning: 500
#       error: 1200
#
### Naming Rules
#
# Note: Can set just the warning level, excluded names, and allowed symbols
# Implicitly:
#   type_name:
#       min_length: 2 # warning
#       max_length:
#           - 40 # warning
#           - 50 # error
#       excluded: iPhone
#       allowed_symbols: ["_"]
# Explicitly:
#   nesting:
#       function_level:
#           warning: 5
#           error: 6
#       type_level:
#           warning: 5
#           error: 6

attributes:
  attributes_with_arguments_always_on_line_above: false

cyclomatic_complexity:
  ignores_case_statements: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  [Pixel, PixelTests]+
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} Pixel\. All rights reserved\.
                    \/\/

large_tuple: 3

nesting:
  type_level: 2

type_contents_order:
    order: [
      [associated_type, type_alias],
      [subtype],
      [case],
      [type_property],
      [type_method],
      [deinitializer, initializer, instance_property],
      [view_life_cycle_method],
      [other_method],
      [subscript]
    ]

# Note: May need to be uncommented
#type_body_length: 500

### MARK: SwiftLint Configuration

# If true, will not cause an Xcode build error if no lintable files are found
allow_zero_lintable_files: false

# Excluded files/folders from linter
excluded:
  - Package.swift

# Reporter type to use, options:
# (checkstyle, codeclimate, csv, emoji, github-actions-logging, html, json, junit, markdown, sonarqube, summary, xcode)
reporter: "xcode"

# If true, all SwiftLint warnings will become errors
# Note: Commented out for now to speed up development
#strict: true
