name: Pull Request Verification

on:
  pull_request:
    types: [ edited, labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  check_issue_linked:
    name: Check Issue Linked
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
    - name: Check linked issue(s)
      uses: nearform-actions/github-action-check-linked-issues@v1
      with:
        custom-body-comment: 'No linked issues found. Please link the corresponding issue(s) to the pull request under development.'
        exclude-labels: 'hotfix'
