name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_package:
    name: Build Swift Package
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Package
      run: swift build -v -Xswiftc "-sdk" -Xswiftc "$(xcrun --sdk iphonesimulator --show-sdk-path)" -Xswiftc "-target" -Xswiftc "arm64-apple-ios17.0-simulator"

  test_package:
    name: Test Swift Package
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Package Tests
      run: swift test -v
