name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_package:
    name: Build Swift Package
    runs-on: macos-latest
    steps:
    - name: Checkout from repository
      uses: actions/checkout@v4
    - name: Fetch cached derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: build-cache-${{ runner.os }}-${{ github.event.head.sha }}
        restore-keys: build-cache-${{ runner.os }}-
    - name: Build package ( iPhone 15 Pro, iOS 17.0)
      run: xcodebuild -scheme Pixel -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' build
    - name: Build package ( iPhone 16 Pro, iOS 18.0)
      run: xcodebuild -scheme Pixel -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' build

  test_package:
    name: Test Swift Package
    runs-on: macos-latest
    steps:
    - name: Checkout from repository
      uses: actions/checkout@v4
    - name: Fetch cached derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: build-cache-${{ runner.os }}-${{ github.event.head.sha }}
        restore-keys: build-cache-${{ runner.os }}-
    - name: Test package ( iPhone 15 Pro, iOS 17.0)
      run: xcodebuild test -scheme PixelTests -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0'
    - name: Test package ( iPhone 16 Pro, iOS 18.0)
      run: xcodebuild test -scheme PixelTests -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0'
