name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_package:
    name: Build Swift Package
    runs-on: macos-latest
    steps:
    - name: Checkout from repository
      uses: actions/checkout@v4
    - name: Cache derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: build-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: build-cache-${{ runner.os }}-
    - name: Build package ( iPhone 15 Pro, iOS 15.0)
      run: xcodebuild -scheme Pixel -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' build

#  test_package:
#    name: Test Swift Package
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v4
#    - name: Run package tests
#      run: swift test -v
